// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewComment struct {
	UserID   string `json:"user_id"`
	VideoID  string `json:"video_id"`
	ParentID string `json:"parent_id"`
	Comment  string `json:"comment"`
}

type NewUser struct {
	Name              string `json:"name"`
	Email             string `json:"email"`
	ProfilePict       string `json:"profile_pict"`
	ChannelBackground string `json:"channel_background"`
	Premium           bool   `json:"premium"`
}

type NewVideo struct {
	UserID      string  `json:"user_id"`
	LocationID  string  `json:"location_id"`
	Title       string  `json:"title"`
	Thumbnail   string  `json:"thumbnail"`
	Link        string  `json:"link"`
	View        int     `json:"view"`
	Description *string `json:"description"`
	Restriction bool    `json:"restriction"`
}
